// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Poulina.GestionMs.Data.Context;

namespace Poulina.GestionMs.Data.Migrations
{
    [DbContext(typeof(GestionMSContext))]
    [Migration("20200408145329_Micro")]
    partial class Micro
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Poulina.GestionMS.Domain.Models.Domaine", b =>
                {
                    b.Property<Guid>("IdDomaine")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nom");

                    b.HasKey("IdDomaine");

                    b.ToTable("Domaine");
                });

            modelBuilder.Entity("Poulina.GestionMS.Domain.Models.Language", b =>
                {
                    b.Property<Guid>("IdL")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Label");

                    b.HasKey("IdL");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("Poulina.GestionMS.Domain.Models.MS", b =>
                {
                    b.Property<Guid>("IdMS")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Author");

                    b.Property<string>("Description");

                    b.Property<string>("DiagClass");

                    b.Property<string>("Label");

                    b.Property<Guid>("LanguageFK");

                    b.Property<string>("Lien");

                    b.HasKey("IdMS");

                    b.HasIndex("LanguageFK");

                    b.ToTable("Microservice");
                });

            modelBuilder.Entity("Poulina.GestionMS.Domain.Models.Methode", b =>
                {
                    b.Property<Guid>("IdMethod")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<Guid>("FK_MS");

                    b.Property<string>("Input");

                    b.Property<string>("Nom");

                    b.Property<string>("Output");

                    b.HasKey("IdMethod");

                    b.HasIndex("FK_MS");

                    b.ToTable("Methodes");
                });

            modelBuilder.Entity("Poulina.GestionMS.Domain.Models.Projet", b =>
                {
                    b.Property<Guid>("IdProjet")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Nom");

                    b.HasKey("IdProjet");

                    b.ToTable("Projets");
                });

            modelBuilder.Entity("Poulina.GestionMS.Domain.Models.ProjetDomain", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("IdDomaine");

                    b.Property<Guid>("IdProjet");

                    b.HasKey("Id");

                    b.HasIndex("IdDomaine");

                    b.HasIndex("IdProjet");

                    b.ToTable("ProjetDomain");
                });

            modelBuilder.Entity("Poulina.GestionMS.Domain.Models.ProjetMS", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("IdMS");

                    b.Property<Guid>("IdProjet");

                    b.HasKey("Id");

                    b.HasIndex("IdMS");

                    b.HasIndex("IdProjet");

                    b.ToTable("ProjetMS");
                });

            modelBuilder.Entity("Poulina.GestionMS.Domain.Models.VersionLanguage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("FK_L");

                    b.Property<Guid>("FK_V");

                    b.Property<Guid>("IdL");

                    b.Property<Guid>("IdVersion");

                    b.HasKey("Id");

                    b.HasIndex("FK_L");

                    b.HasIndex("FK_V");

                    b.ToTable("VersionLanguage");
                });

            modelBuilder.Entity("Poulina.GestionMS.Domain.Models.Versions", b =>
                {
                    b.Property<Guid>("IDversion")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Numero");

                    b.HasKey("IDversion");

                    b.ToTable("Versions");
                });

            modelBuilder.Entity("Poulina.GestionMS.Domain.Models.MS", b =>
                {
                    b.HasOne("Poulina.GestionMS.Domain.Models.Language", "Languages")
                        .WithMany("Microservices")
                        .HasForeignKey("LanguageFK")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Poulina.GestionMS.Domain.Models.Methode", b =>
                {
                    b.HasOne("Poulina.GestionMS.Domain.Models.MS", "Microservices")
                        .WithMany("Methods")
                        .HasForeignKey("FK_MS")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Poulina.GestionMS.Domain.Models.ProjetDomain", b =>
                {
                    b.HasOne("Poulina.GestionMS.Domain.Models.Domaine", "Domaine")
                        .WithMany("ProjetDomains")
                        .HasForeignKey("IdDomaine")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Poulina.GestionMS.Domain.Models.Projet", "Projets")
                        .WithMany("ProjetDomains")
                        .HasForeignKey("IdProjet")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Poulina.GestionMS.Domain.Models.ProjetMS", b =>
                {
                    b.HasOne("Poulina.GestionMS.Domain.Models.MS", "Microservices")
                        .WithMany("ProjetMs")
                        .HasForeignKey("IdMS")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Poulina.GestionMS.Domain.Models.Projet", "Projets")
                        .WithMany("ProjetMs")
                        .HasForeignKey("IdProjet")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Poulina.GestionMS.Domain.Models.VersionLanguage", b =>
                {
                    b.HasOne("Poulina.GestionMS.Domain.Models.Language", "Languages")
                        .WithMany("LanguageVersions")
                        .HasForeignKey("FK_L")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Poulina.GestionMS.Domain.Models.Versions", "Versions")
                        .WithMany("LanguageVersions")
                        .HasForeignKey("FK_V")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
